//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankMonitor.datasource
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_CHUYENTIEN
    {
        public int MAGD { get; set; }
        public string SOTK_CHUYEN { get; set; }
        public System.DateTime NGAYGD { get; set; }
        public decimal SOTIEN { get; set; }
        public string SOTK_NHAN { get; set; }
        public string MANV { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
