//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankMonitor.datasource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Configuration;
    using System.Windows;


    public partial class NGANHANG : DbContext
    {
        public NGANHANG()
            : base(GetConnectionString())
        {
        }

        public void ChangeDataSource(String serverName)
        {
            Configuration config;
            config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
           
            string connectionString = config.ConnectionStrings.ConnectionStrings["NGANHANG"].ConnectionString;
            connectionString = connectionString.Replace(@"PC-DOM\MSSQLSERVER0", serverName);
            config.ConnectionStrings.ConnectionStrings["NGANHANG"].ConnectionString = connectionString;
            config.Save(ConfigurationSaveMode.Modified);
            ConfigurationManager.RefreshSection("connectionStrings");
        }
        public static string GetConnectionString()
        {
            Configuration config;
            config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
            return  config.ConnectionStrings.ConnectionStrings["NGANHANG"].ConnectionString;
        }

        public void RefreshAll()
        {
            foreach (var entity in this.ChangeTracker.Entries())
            {
                entity.Reload();
            }
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<GD_CHUYENTIEN> GD_CHUYENTIEN { get; set; }
        public virtual DbSet<GD_GOIRUT> GD_GOIRUT { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    

    }
}
