//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankMonitor.datasource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Configuration;
    using System.Windows;
    using System.Text.RegularExpressions;
    using model;

    public partial class NGANHANG : DbContext
    {
        User user;
        public NGANHANG()
            : base(GetConnectionString())
        {
        }

        public void ChangeDataSource()
        {
            Configuration config;
            config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
           
            string connectionString = config.ConnectionStrings.ConnectionStrings["NGANHANG"].ConnectionString;
            connectionString = Regex.Replace(connectionString, @"PC-DOM\\MSSQLSERVER.", user.Distribute);
            connectionString = Regex.Replace(connectionString, @"user id=\w*;", "user id=" + user.Username + ";"); 
            connectionString = Regex.Replace(connectionString, @"password=\w*;", "password=" + user.Password + ";");
         
            config.ConnectionStrings.ConnectionStrings["NGANHANG"].ConnectionString = connectionString;
            config.Save(ConfigurationSaveMode.Modified);
            ConfigurationManager.RefreshSection("connectionStrings");
        }
        public static string GetConnectionString()
        {
            Configuration config;
            config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
            return  config.ConnectionStrings.ConnectionStrings["NGANHANG"].ConnectionString;
        }

        public void RefreshAll()
        {
            foreach (var entity in this.ChangeTracker.Entries())
            {
                entity.Reload();
            }
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<GD_CHUYENTIEN> GD_CHUYENTIEN { get; set; }
        public virtual DbSet<GD_GOIRUT> GD_GOIRUT { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }

        internal User User
        {
            get
            {
                return user;
            }

            set
            {
                user = value;
            }
        }
    }
}
